# Generated by Django 3.2.4 on 2021-06-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holisy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='person_count',
            field=models.IntegerField(default=1, verbose_name='Количество жильцов'),
        ),
    ]
