# Generated by Django 3.2.4 on 2021-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holisy_app', '0002_booking_person_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('p', 'Ожидает оплаты'), ('v', 'На подтверждении'), ('l', 'В процессе'), ('c', 'Завершен')], default='v', max_length=1, verbose_name='Статус'),
        ),
    ]
